name: Run CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'requirements_dev.txt'
      - 'requirements.txt'
      - '*.py'
      - 'utils/**'
      - 'workdir/**'
      - 'data/**'
      - 'Dockerfile'
      - '.dockerignore'

env:
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/pocket-cfdm:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build image'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.LATEST_TAG }}
      - name: 'Inspect'
        run: docker image inspect ${{ env.LATEST_TAG }}
